name: Daily Auto Commit

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update log file
        run: |
          echo "Commit on $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name "Rahul Goswami"
          git config --global user.email "therahulgoswami99@gmail.com"
          git add .
          git commit --allow-empty -m "Daily auto commit"
          git push